### ISSUE TITLE
Backport to SS3

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#119]
We should break this out into:

For MFA:
- [x] Ensure the login handler works (#149)
- [x] Break up the JS (#150)
- [x] Confirm standalone JS injector provides its own redux store (#151)

For methods:
- [x] Backport of TOTP (https://github.com/silverstripe/silverstripe-totp-authenticator/issues/18)
- [x] Backport of WebAuthn (https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/19)

Related modules:
- [x] Backport and confirm login-forms work (https://github.com/silverstripe/silverstripe-login-forms/issues/24)
- [x] Backport and confirm security-extensions work (https://github.com/silverstripe/silverstripe-security-extensions/issues/10)

**Comment by robbieaverill** [comment]
This looks kind of like an epic rather than an actionable issue. I've updated the links and sub-tasks to reflect the current state of play.

**Comment by Cheddam** [comment]
The SS3 backport is complete, bar some minor bugs and changes to be backported. Closing this out.
