### ISSUE TITLE
MFA URL handlers need to check sudo mode status on GET routes as well

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#187]
Locally I've set sudo mode timeout to 5 minutes. If you refresh the page enough times after initially entering your password during a login flow (not completing MFA, but debugging something), you eventually get 403 failures from the method handler endpoints because sudo mode has expired. The `Security/login/default/mfa` route should really catch this first and send you on your way (back to login with the session message flashing up).

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/218

### Sub-tasks

- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/issues/20
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/32

**Comment by robbieaverill** [comment]
For simplicity we could move the sudo mode checks to an init function maybe...

**Comment by robbieaverill** [comment]
This is more obvious when sudo mode lifetime is low. cc @brynwhyman

**Comment by brynwhyman** [comment]
Yes, let's fix this. Would be worth looking at the sudo mode timeout at the same time

**Comment by robbieaverill** [comment]
Sudo mode lifetime is now 45 mins by default - see https://github.com/silverstripe/silverstripe-security-extensions/issues/5

**Comment by NightJar** [comment]
Merged the above.
Does this sudo mode timeout extend through a session? I.e. If a session expires (in 25 minutes on CWP) then the user logs back in and tries to perform a sudo mode action before the 45 minute default is up, is sudo mode still enabled?
Or does it expire with the session despite what the configuration is for it?

**Comment by robbieaverill** [comment]
In that case the session would expire and you’d need to log back in, resetting sudo mode’s lifetime. For sudo mode to kick in you need to use the cms at least once for every session timeout limit until the sudo mode lifetime is reached

**Comment by NightJar** [comment]
Cool, I see that in Security Extension's readme, so this is done :)

**Comment by robbieaverill** [comment]
That PR doesn’t resolve this issue, sorry for any miscommunication
