### ISSUE TITLE
[Demo issue] Mobile view of MFA looks broken 

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#253]
Graphic squashes out text on mobile view. consider display none media query. All mobile views with this kind of layout would need to considered.

Note. Removing this graphics might cause text to be really close action buttons. Hence, consider adding top margin ~20px to action button holder.

issue tracked in toybox: http://app.toyboxsystems.com/magic/qtfyB2jxqVYT

![clustertest2-uat.cwp.govt.nz_Security_login_default_mfa.png](https://images.zenhubusercontent.com/596d365561b4ca3b0a74bd86/f0c29115-013c-460b-bd13-3354fe71a947)

## Pull requests

- [x] login-forms: silverstripe/silverstripe-login-forms#34
- [x] webauthn-authenticator: silverstripe/silverstripe-webauthn-authenticator#51
- [x] totp-authenticator silverstripe/silverstripe-totp-authenticator#31
- [ ] https://github.com/silverstripe/silverstripe-mfa/pull/307

**Comment by NightJar** [comment]
PRs:
- login-forms: https://github.com/silverstripe/silverstripe-login-forms/pull/34
- webauthn-authenticator: https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/51
- totp-authenticator https://github.com/silverstripe/silverstripe-totp-authenticator/pull/31

**Comment by robbieaverill** [comment]
Backup codes still needs its graphic removed:

![image](https://user-images.githubusercontent.com/5170590/62334499-063ec700-b51c-11e9-8856-9895aa2bfc29.png)

**Comment by robbieaverill** [comment]
Oops - missed a PR: https://github.com/silverstripe/silverstripe-mfa/pull/307

**Comment by ScopeyNZ** [comment]
#307 is merged
